### ISSUE TITLE
Isporučiti prvu verziju aplikacije

### ISSUE THREAD

**Issue by Pizzalol** [AIR-FOI-HR/AIR1918#45]
Isporuka prve verzije aplikacije nakon prvog sprinta

- [x] Android APK
- [ ] Korisnička dokumentacija

**Comment by Pizzalol** [comment]
Isporučena verzija nakon prvog sprinta nalazi se na sljedećoj poveznici https://www.dropbox.com/s/91c4syer7g18vcj/2Fit4U.apk?dl=0

**Comment by Mpehnec** [comment]
Korisnička dokumentacija za prvu iteraciju 2FIT4YOU aplikacije

[https://app.zenhub.com/files/217942747/66776b08-c362-4531-98af-35e120008d60/download](https://app.zenhub.com/files/217942747/66776b08-c362-4531-98af-35e120008d60/download)
