### ISSUE TITLE
Sprint 2 - završni sastanak

### ISSUE THREAD

**Issue by Mpehnec** [AIR-FOI-HR/AIR1918#59]
Završni sastanak za drugi sprint

**Comment by Pizzalol** [comment]
Odrađen je završni sastanak drugoga sprinta dana 25.01.2020. te je istodobno izrađena retrospektiva sprinta. Retrospektiva je dostupna [ovdje](https://docs.google.com/document/d/1QfL3Qf-zqE4dpIEP4PSXCVsVxb4zFxcAh-pbDcdcXF0/edit?usp=sharing).
